-- MySQL Script generated by MySQL Workbench
-- Sun Jun 21 15:16:41 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema hangman
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema hangman
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `hangman` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `hangman` ;

-- -----------------------------------------------------
-- Table `hangman`.`difficulty`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hangman`.`difficulty` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `timeinminutes` INT(11) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `hangman`.`highscore`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hangman`.`highscore` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `difficultyid` INT(11) NOT NULL,
  `time` BIGINT(20) NULL DEFAULT NULL,
  `player` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_highscore_difficulty_idx` (`difficultyid` ASC) VISIBLE,
  CONSTRAINT `fk_highscore_difficulty`
    FOREIGN KEY (`difficultyid`)
    REFERENCES `hangman`.`difficulty` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 49
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `hangman`.`quizquestion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hangman`.`quizquestion` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `questiontext` VARCHAR(100) NULL DEFAULT NULL,
  `answer` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 34
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `hangman`.`word`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hangman`.`word` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `difficultyid` INT(11) NOT NULL DEFAULT '1',
  `wordtext` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_word_difficulty_idx` (`difficultyid` ASC) VISIBLE,
  CONSTRAINT `fk_word_difficulty`
    FOREIGN KEY (`difficultyid`)
    REFERENCES `hangman`.`difficulty` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 37
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
