package GUIS;

import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author shnva
 */
public class Settings extends javax.swing.JFrame {
    private final Classes.Settings settings;

    /**
     * Creates new form Settings
     *
     * @param settings
     */
    public Settings(Classes.Settings settings) {
        this.settings = settings;
        initComponents();
        fillWordsList();
    }

    public final void fillWordsList() {
        //first, clear all existing elements. to make sure no duplicates will be found
        lstWords.setModel(new DefaultListModel());
        //set new model, filled with all words in the word table
        lstWords.setModel(new javax.swing.AbstractListModel<String>() {
            String[] items = settings.getAllWords().stream().map(i -> "(" + i.getId() + ") " + i.getWordText()).toArray(String[]::new);

            @Override
            public int getSize() {
                return items.length;
            }

            @Override
            public String getElementAt(int i) {
                return items[i];
            }
        });
        
        //select the first item in the list
        lstWords.setSelectedIndex(0);
    }

    public final void editSelectedWord(String wordText) {
        //set selected difficulty id in combobox, listitems are ordered by id, starting at index 0
        settings.setSelectedWord(settings.getSelectedWord(wordText));
        txtWordText.setText(settings.getSelectedWord().getWordText());
        cbDifficulty.setSelectedIndex(settings.getSelectedWord().getDifficulty().getValue() - 1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lstWords = new javax.swing.JList<>();
        btnSaveWord = new javax.swing.JButton();
        btnExitSettings = new javax.swing.JButton();
        txtWordText = new javax.swing.JTextField();
        lblWord = new javax.swing.JLabel();
        lblDifficulty = new javax.swing.JLabel();
        cbDifficulty = new javax.swing.JComboBox<>();
        btnNewWord = new javax.swing.JButton();
        btnRemoveWord = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);

        lstWords.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstWordsValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lstWords);

        btnSaveWord.setText("Save");
        btnSaveWord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveWordActionPerformed(evt);
            }
        });

        btnExitSettings.setText("Exit");
        btnExitSettings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitSettingsActionPerformed(evt);
            }
        });

        lblWord.setText("Text:");

        lblDifficulty.setText("Difficulty:");

        cbDifficulty.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Easy", "Medium", "Hard" }));

        btnNewWord.setText("New");
        btnNewWord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewWordActionPerformed(evt);
            }
        });

        btnRemoveWord.setText("Remove");
        btnRemoveWord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveWordActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnNewWord, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnRemoveWord, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSaveWord, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnExitSettings, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDifficulty)
                            .addComponent(lblWord, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtWordText)
                            .addComponent(cbDifficulty, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblWord)
                            .addComponent(txtWordText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDifficulty)
                            .addComponent(cbDifficulty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSaveWord)
                            .addComponent(btnExitSettings)
                            .addComponent(btnNewWord)
                            .addComponent(btnRemoveWord))))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lstWordsValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstWordsValueChanged
        // TODO add your handling code here:
        String value = lstWords.getSelectedValue();
        //This line prevents double events
        if (!evt.getValueIsAdjusting()) {
            //only proceed if there is any listitem selected
            if (value != null) {
                //fill the screen with info from currently selected Word
                editSelectedWord(value);
            }
        }
    }//GEN-LAST:event_lstWordsValueChanged

    private void btnSaveWordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveWordActionPerformed
        // TODO add your handling code here:
        //save current word with all parameters
        String wordText = txtWordText.getText();
        if (wordText.equals("")) {
            JOptionPane.showMessageDialog(this, "Er is geen tekst ingevoerd!");
        } else {
            settings.saveWord(wordText, cbDifficulty.getSelectedIndex() + 1);
            fillWordsList();
        }
    }//GEN-LAST:event_btnSaveWordActionPerformed

    private void btnRemoveWordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveWordActionPerformed
        // TODO add your handling code here:
        settings.removeSelectedWord();
        //refill the listbox again with the updated collection
        fillWordsList();
    }//GEN-LAST:event_btnRemoveWordActionPerformed

    private void btnNewWordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewWordActionPerformed
        // TODO add your handling code here:
        this.settings.newWord();
        lstWords.setSelectedIndex(-1);
        txtWordText.setText("");
        cbDifficulty.setSelectedIndex(0);
    }//GEN-LAST:event_btnNewWordActionPerformed

    private void btnExitSettingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitSettingsActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_btnExitSettingsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExitSettings;
    private javax.swing.JButton btnNewWord;
    private javax.swing.JButton btnRemoveWord;
    private javax.swing.JButton btnSaveWord;
    private javax.swing.JComboBox<String> cbDifficulty;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDifficulty;
    private javax.swing.JLabel lblWord;
    private javax.swing.JList<String> lstWords;
    private javax.swing.JTextField txtWordText;
    // End of variables declaration//GEN-END:variables
}
